# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FloodRiskAnalyzer
                                 A QGIS plugin
 FloodRisk Analyzer: QGIS Plugin for Flood Risk Classification
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-09
        copyright            : (C) 2025 by Andre Nogueira Sousa
        email                : andrenogsousa@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FloodRiskAnalyzer class from file FloodRiskAnalyzer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flood_risk import FloodRiskAnalyzer
    return FloodRiskAnalyzer(iface)
